export const inputMascota = document.querySelector('#mascota'); 
export const inputPropietario = document.querySelector('#propietario'); 
export const inputTelefono = document.querySelector('#telefono'); 
export const inputFecha = document.querySelector('#fecha'); 
export const inputHora = document.querySelector('#hora'); 
export const inputSintomas = document.querySelector('#sintomas'); 
export const boton = document.querySelector('.form-group button');
export const formulario = document.querySelector('#nueva-cita')
export const contenedorCitashtml = document.querySelector('#citas')